### PR TITLE
feat(spinner): add spinner icon

### PR DESCRIPTION
**Pull request by mt-rory**
## Summary
Add Spinner Icon
Screen Shot 2020-04-06 at 14 33 29

### CODE REVIEW

**Comment by mt-roberto** [comment]
@mt-rory What is this icon used for?

**Comment by mt-rory** [comment]
> this icon used for?

For this screen https://www.figma.com/file/F11hvKQKDBK5TngIPSQlOD/Master-Screens?node-id=1004%3A657

**Comment by mt-roberto** [comment]
Ok, as discussed with Rory, this icon can't be customized because it only takes one color.

**Comment by mt-roberto** [comment]
I would create a react component for this in the project, so that you can pass props to customize it. It can still be an SVG.

**Pull request merged**
